name: "GH Docs Bot Builder"
description: "Builds and runs the custom C++ Static Site Generator."
author: "Robert Zheng"
inputs:
  template:
    description: "Path to HTML template file"
    required: false
    default: "theme/desktop/fluid_template.html"
  output:
    description: "Output directory for generated HTML"
    required: false
    default: "public"
  docs:
    description: "Directory containing markdown documentation"
    required: false
    default: "docs"
  assets:
    description: "Directory containing additional assets"
    required: false
    default: "theme/fluid/assets"
  base_path:
    description: "Base path for the generated site"
    required: false
    default: ""
  toc:
    description: "Enable Table of Contents"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        sudo apt-get update || true
        sudo apt-get install -y libmd4c-dev libmd4c-html0 libmd4c-html0-dev libmd4c0 libzip5 libpugixml1v5

    - name: get AppImage
      shell: bash
      run: |
        wget https://github.com/Zheng-Bote/gha_ghpages/releases/download/v1.9.0/SSG_gh_docs_bot-x86_64.AppImage
        chmod +x SSG_gh_docs_bot-x86_64.AppImage

    - name: get Plugins
      shell: bash
      run: |
        wget https://github.com/Zheng-Bote/gha_ghpages/releases/download/v1.9.0/plugins.tar.gz
        tar -xvf plugins.tar.gz

    - name: Create Configuration
      shell: bash
      run: |
        echo "[General]" > config.cfg
        echo "template=${{ inputs.template }}" >> config.cfg
        echo "assets=${{ inputs.assets }}" >> config.cfg
        echo "output=${{ inputs.output }}" >> config.cfg
        echo "base_path=${{ inputs.base_path }}" >> config.cfg
        echo "toc=${{ inputs.toc }}" >> config.cfg
        echo "[plugins]" >> config.cfg
        echo "path=./plugins" >> config.cfg
        echo "enabled=markdown, html, toc, asciidoc, search, sitemap, mermaid, breadcrumb, reading_time, shortcode, minify, office, info, emoji" >> config.cfg
        echo "[reading_time]" >> config.cfg
        echo "threshold=200" >> config.cfg
        echo "wpm=200" >> config.cfg

    - name: Run AppImage
      shell: bash
      run: |
        ./SSG_gh_docs_bot-x86_64.AppImage --appimage-extract-and-run config.cfg ${{ inputs.docs }}
